### ISSUE TITLE
Default binning

### ISSUE THREAD

**Issue by saschacaron** [NLeSC/spot#103]
Change default binning from 15 to 20 (better to divide by ranges upper and lower ends),
maybe round min and maximum

**Comment by jiskattema** [comment]
I'm not sure what a sensible default is. so lets try 20 instead of 15.
Rounding start and end ranges is not done on purpose; at the moment this would also round range selection on scatter plots and be very confusing/annoying.
If rounded ranges are desired, you can force ranges (and binning) for parameters in the session file.
