### ISSUE TITLE
Demo hangs

### ISSUE THREAD

**Issue by egpbos** [NLeSC/spot#119]
Reproduce:

- Go to http://nlesc.github.io/spot (which by the way "redirects" to http://nlesc.github.io, i.e. the URL in the address bar changes to that once the page has loaded... very strange, but different issue).
- Start the demo.
- Click one of the points in the *avg FamilySize by Age Fare* facet.
- Click the button with the three horizontal lines at the top of the facet.

Happens both in Safari 11.0 and in Firefox 55.0.3 on macOS 10.12.6.

**Comment by jiskattema** [comment]
I cannot reproduce it. Please show me (screenshot?) what button you press in the last step.

**Comment by fdiblen** [comment]
Thanks for reporting!
The 'redirecting' issue is a known problem of Github pages. The relative urls causes this. We are working on it.

The demo should be fully functional in Chrom/Chromium browser.

**Comment by egpbos** [comment]
The same problem occurs in Chrome...
<img width="227" alt="schermafbeelding 2017-10-17 om 11 41 30" src="https://user-images.githubusercontent.com/6146598/31658007-276924c4-b330-11e7-9302-08e0e2a31889.png">
It's the button with the three bars (encircled in grey in the screenshot).

**Comment by jspaaks** [comment]
same here (Firefox 56.0 64-bit). Strictly speaking Firefox is not a supported browser though.

**Comment by egpbos** [comment]
It's probably a generic javascript bug though, since the bug exists on all major browsers.

**Comment by fdiblen** [comment]
The use of zoom-in feature for the bubble chart is slightly different than other charts.
You need to select a region to zoom-in:
select the first and the second points and click on zoom-in button
![bubbleplot](https://user-images.githubusercontent.com/144492/31663526-b031d6ae-b342-11e7-9655-64abb9ff0c69.png)

However, this is something we should fix. User may want to zoom-in a single data point.

**Comment by jspaaks** [comment]
It's probably fine as long as you are explicit about what user input is required at a certain stage during selection, because apparently, both @egpbos and me could not figure it out from just the feedback that the interface provides, leading us to believe that the app was in fact broken. I'm assuming that you/@fdiblen can make it work for you, because you know the (currently implicit) protocol/recipe to make it do what you want. The trick is to make the recipe _explicit_ by telling users about what to do next during selection.
