### ISSUE TITLE
Selecting multiple items is not intuitive

### ISSUE THREAD

**Issue by dafnevk** [NLeSC/spot#51]
Selecting multiple data points (for example in the bar chart or pie chart) is not always intuitive. I would expect that it selects each bar/part/point that I click individually, and unselects it again when I click it again.

**Comment by jiskattema** [comment]
Yes, it is confusing..
The behavior depends on the type of facet:
1. Categorial Facets: clicking on items adds/removes them from the selection. When only one item is (de-)selected, clicking on it inverts the selection.

2. Other facets: the selection is actually an interval [start,end]. clicking on any point will grow/shrink the interval to contain the selected point by moving the closest edge of the interval.

This was also a compromise because we were using mouse clicks on empty space in the chart to clear the selection (this now works via a button). If you can come up with more natural behavior, please let me know.

Another option is to use visual clues (handlebars etc. on the selected region)
